version: '3.8'

services:
  app:
    image: tool-registry:2.0.0
    container_name: tool-registry-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=yoursecretkey
      - AUTH_DISABLED=true
      - METRICS_ENABLED=true
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tool_registry
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=tool_registry
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - tool_registry_data:/data

  db:
    image: postgres:14
    container_name: tool-registry-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tool_registry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: tool-registry-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./genai-tool-explorer
      dockerfile: Dockerfile
    container_name: tool-registry-frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      - app

volumes:
  tool_registry_data:
  postgres_data:
  redis_data: 