# Docker Compose file for Tool Registry API - Production
# Includes app (API), PostgreSQL database, Redis, documentation server and frontend

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tool-registry:2.0.0  # Updated to version 2.0.0 - Production-ready
    container_name: tool-registry-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/toolregistry
      - REDIS_URL=redis://redis:6379/0
      - APP_VERSION=2.0.0
      - DEBUG=false
      - AUTH_DISABLED=true
      - METRICS_ENABLED=true
      - LOG_LEVEL=INFO
      # Add CORS configuration to allow frontend requests
      - CORS_ORIGINS=http://localhost:80,http://frontend:80,http://localhost
      - TEST_MODE=false
    volumes:
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: tool-registry-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=toolregistry
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: tool-registry-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  docs:
    image: python:3.9-slim
    container_name: tool-registry-docs
    volumes:
      - ./postman:/postman
    ports:
      - "9000:9000"
    working_dir: /postman
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y --no-install-recommends python3-pip && 
        pip install --no-cache-dir flask && 
        python server.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/tool_registry_api_collection.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  frontend:
    build:
      context: ./genai-tool-explorer
      dockerfile: Dockerfile
    container_name: tool-registry-frontend
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 